### ISSUE TITLE
Feature request : AM/PM versus 24h time format

### ISSUE THREAD

**Issue by robertrub** [bassettb/SugarPiDisplay#13]
When/if you have some free time, it would be nice to have the AM/PM vs 24h time display option on the setup screen.

**Comment by bassettb** [comment]
Good idea.  I'll add that.  
I should probably do mg/dl vs mmol/l also.

**Comment by robertrub** [comment]
Tnx :) I think mmol/l would be useful to others too. 

Mine is standing on my nightstand. The BGs are too small (without my glasses on my nose...) on my watch. I see the numbers  clear enough even without glasses on the rpi+e-paper ;) I need to find a way to light a mini LED to see the screen on demand.

**Comment by bassettb** [comment]
I merged in the changes for 24hour setting just now.  I need to research how the Dexcom and NS APIs handle mmol/L before I make that change.  But it should be soon.  How many decimal places are typical with mmol/L ?
It should be easy to solder a tiny LED onto VCC and GND pins under the hat.

**Comment by robertrub** [comment]
Great, I'll test it. 

For the mmol, I suppose the 3 numbers x.xx (as with mg/ml) should be OK (I don't have a formal data on this, just my basic logic)

Is there an easy way to update your program on my rpi (I'm quite recent to git and linux) ?

I'd thought of soldering a LED but my wife like to sleep in "total" darkness... I had to "hide" the LED of the rpi ;) I made a a 3 LED mini lamp with a variable resistance set to almost min and a button... All this, in a Contour Next One strip box ;)

**Comment by bassettb** [comment]
You be able to:
`cd SugarPiDisplay`
`git pull`
`sudo reboot`

**Comment by robertrub** [comment]
Tnx. Update very easy. 24 hours format in place and working :)
FYI, on several screen captures, mmol/lt have only 1 digit after the decimal point.
