### ISSUE TITLE
Default config file

### ISSUE THREAD

**Issue by triomen** [bassettb/SugarPiDisplay#22]
Hi,

After setup the project, I had several error saying there is not config available, with an error L31 here : 
https://github.com/bassettb/SugarPiDisplay/blob/29be81cbabee917ccba71714262d2b065a09b379/sugarpidisplay/epaper_display.py#L31

I manage to fix the setup by hardcoding default values in this file. After that, config interface on :8080 was available and I managed to set up config through the interface.
Maybe create a default config file in install.sh ?

**Comment by bassettb** [comment]
Sorry about this bug.  
I specify defaults in code, but I recently introduced a bug that causes a failure when there is no config file.  Fix is here: #24

**Comment by bassettb** [comment]
The fix is merged.  Glad you were able to work around it.  Thanks for taking the time to report it.
