### ISSUE TITLE
Strange line on the screen 

### ISSUE THREAD

**Issue by robertrub** [bassettb/SugarPiDisplay#26]
Hi

I hadn't used sugarpi for some time. I found it recently. Now, I have a line in the middle of the BGs. It is still there (same position compared to the BGs) if I activate the graph (BGs move left). 

![20230629_120105.jpg](https://github.com/bassettb/SugarPiDisplay/assets/76626474/d61de4d9-81cf-47df-bb57-42ec10698539)

**Comment by bassettb** [comment]
That line indicates that the data is stale.  90 was the last reading, but it was from more than 20 minutes ago.

**Comment by robertrub** [comment]
Thanks. I had guessed it was the same as the barred BGs in AAPS but forgot to delete my question from GitHub.

The line disappeared as soon as the arrow was back.

Stil working great with NS and Mongo db on personal NAS.

Regards :)
