### ISSUE TITLE
Support for European Server(s)

### ISSUE THREAD

**Issue by pjapk** [bassettb/SugarPiDisplay#30]
I believe European users connect to a different server to US users - can this be added as a config option?

**Comment by bassettb** [comment]
That shouldn't be too tough.  I'll get something to you by next week.

**Comment by bassettb** [comment]
@pjapk  This change has been merged.  There is now an "Outside US" setting you can enable.
If you try it out, please let me know how it works for you.

**Comment by pjapk** [comment]
Cool, thanks, will get a chance to try in a few days when I'll have my hands on the Pi again :)
