### ISSUE TITLE
Support for Waveshare ePaper Display?

### ISSUE THREAD

**Issue by tremor** [bassettb/SugarPiDisplay#6]
How hard is it to adapt it for the Waveshare ePaper Displays?
https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(B)
There is a nice 3 color (black/white/red!) HAT for the Raspi Zero W....

**Comment by tremor** [comment]
I have a similar project running: https://github.com/tremor/Nightscout2ePaper
But my parsing of the REST-API is currently very basic. Do you have a documentation for your https://github.com/bassettb/SugarPiDisplay/blob/master/sugarpidisplay/nightscout_reader.py libary? What to I have for inputs, what do I get as output?

**Comment by bassettb** [comment]
I don't have documentation for it.  I'd look at how it is used in sugar_pi_app.py.  There is a state machine that calls the login and handles errors appropriately.  I just pushed an update that cleans it up. 
That screen looks cool.  Would be neat to get the BG graph on there.

**Comment by bassettb** [comment]
I bought one of those displays and I'll add support for it when it arrives.  Thanks for the suggestion.

**Comment by tremor** [comment]
I bought one with an esp32 attached on the back and try to port it to the Arduino IDE. There is already a Python Modul for the esp32 for accessing the epaper and also some code for a simple rest API call

**Comment by tremor** [comment]
I bought this one: https://www.aliexpress.com/item/TTGO-T5s-V1-9-ESP32-2-7-EPaper-Plus-Module-for-Alexa-I2S-DAC-MAX98357A-MEMS/32867880658.html?spm=a2g0s.9042311.0.0.311c4c4d75i3u7

**Comment by bassettb** [comment]
I bought the 2.13inch_e-Paper_HAT_(B) which is the same size as the Pi Zero W.  The test app runs okay, but the screen takes a long time to transition.  It appears to take 5 to 12 seconds to draw the screen.  Did you notice this also?  That might be okay if I only change the screen every 5 minutes.  But I was hoping to show the minutes elapsed in the bottom corner which would update every minute.

**Comment by tremor** [comment]
Yes, the three color epaper needs some seconds till they are ready. I only refresh every 5 Minutes...
You'll need to set the epaper to sleep (LOW on GPIO17) after every refresh or you damage the display...

**Comment by tremor** [comment]
As you can see under https://www.waveshare.com/product/2.13inch-e-paper-hat.htm the refresh timings for the 3-Color Versions are 15 seconds, the 2-color versions only need 1-4 seconds...

**Comment by bassettb** [comment]
I have the code partly done and it looks good on the e-paper, despite the slow refresh on the 3-color I'm testing with.  The 2-color should arrive tomorrow.  I'm going to stick with the 2-color so I get faster refresh.  I'll test that out and push up a branch by the end of the week if you are interested.

**Comment by tremor** [comment]
That would be great, but I have my own try here: https://github.com/tremor/Nightscout2ePaper that works with a raspberry pi w and the waveshare 2.13" Display. My 2,7" ESP32 is here, but I only get some test-content on the epaper, nothing else.

It works, but is no nice code and need some helper files but it switches the controller for the ePaper off after every refresh.

**Comment by tremor** [comment]
>refresh. I'll test that out and push up a branch by the end of the week if you are interested.

Can you push it?

**Comment by bassettb** [comment]
I just pushed up the branch.  I ran it for a few days at home with no issues until I came home one day and the screen had severe burn-in.  I haven't had the time to investigate why yet.  I'm doing a partial write every minute and then a full write every 5 minutes.  I put the screen fully to sleep after every write.

**Comment by tremor** [comment]
Just want to point to my currently running epaper https://github.com/tremor/PlaygroundArduino without burn-in issue or missing lines...

**Comment by bassettb** [comment]
@tremor I finally purchased a 2.13inch display V2 (it looks like waveshare had some bugs in their original hardware and python code).  V2 works great, no burn in.  I also slowed down my refresh rate.  I was updating every minute in order to show how old the BG reading was.  Now I update every 5 minutes.  
I updated this project to use the e-paper display.
